### ISSUE TITLE
Feature: Config files

### ISSUE THREAD

**Issue by a-rokay** [roman-rezinkin/RomanStaticSG#23]
I'd like to add a feature that allows users to provide a config file through a `-c` or `--config` argument. The config file will be JSON formatted and will act as an alternative to passing a bunch of arguments.

###### ssg-config.json
```
{
  "input": "./site",
  "output": "./build"
  "lang": "fr"
}
```
For example:
```
romanssg.py --config ./ssg-config.json
```
The above command will run romanssg.py as if the user passed the arguments manually, like below:

```
romanssg.py --input ./site --output ./build --lang fr
```

**Comment by roman-rezinkin** [comment]
Closed #24
